baseurl = "https://danielzamo.github.io/"
languageCode = "es"
title = "Sitio web estatico"
theme = "ghostwriter"


#[menu]
#[[menu.main]]
#  identifier = 'dns.query.recursive'
#  name = 'Answer dns recursiva'
#  pre = "<i class='fa fa-heart'></i>"
#  url = '/dns.query.recursive/'
#  weight = -110
#[[menu.main]]
#  name = 'dig'
#  post = "<span class='alert'>New!</span>"
#  pre = "<i class='fa fa-road'></i>"
#  url = '/dig/'
#  weight = -100

[Params]
 mainSections = ["post"]
 intro = true
 headline = "Algunos articulos"
 description = "Sitio est√°tico"
 github = "https://github.com/danielzamo"
 twitter = "https://twitter.com/danieloscarzamo"
 email = "daniel.oscar.zamo@gmail.com"
 opengraph = true
 shareTwitter = true
# dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
 post = "/:filename/"
